# setup_jenkins_slave.yml
- hosts: jenkins_slaves
  become: yes
  tasks:
    - name: Create 'jenkins' user
      user:
        name: jenkins
        shell: /bin/bash
        create_home: yes
        state: present

    - name: Allow 'jenkins' passwordless sudo
      lineinfile:
        path: /etc/sudoers
        line: 'jenkins ALL=(ALL) NOPASSWD:ALL'
        validate: 'visudo -cf %s'

    - name: Install Java (OpenJDK 11)
      apt:
        name: openjdk-11-jdk
        update_cache: yes
        state: present

    - name: Install required dependencies for Docker and AWS CLI
      apt:
        name:
          - unzip
          - curl
          - ca-certificates
          - gnupg
          - lsb-release
        update_cache: yes
        state: present

    - name: Add Docker GPG key
      shell: |
        mkdir -p /etc/apt/keyrings
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
      args:
        creates: /etc/apt/keyrings/docker.gpg

    - name: Add Docker APT repository
      shell: |
        echo \
          "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
          $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null

    - name: Install Docker Engine
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        update_cache: yes
        state: present

    - name: Add 'jenkins' user to 'docker' group
      user:
        name: jenkins
        groups: docker
        append: yes

    - name: Install AWS CLI v2
      shell: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip -q awscliv2.zip
        ./aws/install
      args:
        creates: /usr/local/bin/aws

    - name: Create Jenkins agent directory
      file:
        path: /home/jenkins/jenkins_slave
        state: directory
        owner: jenkins
        group: jenkins
        mode: '0755'
   